# Generated by Django 4.1.13 on 2024-11-19 09:10

from django.db import migrations, models
import systems.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FormSubmission',
            fields=[
                ('created', models.DateTimeField(editable=False, null=True)),
                ('updated', models.DateTimeField(editable=False, null=True)),
                ('id', models.CharField(editable=False, max_length=64, primary_key=True, serialize=False)),
                ('portal_name', models.CharField(default=None, max_length=256, null=True)),
                ('name', models.CharField(default=None, max_length=256, null=True)),
                ('external_id', models.CharField(default=None, max_length=256, null=True)),
                ('fields', systems.models.fields.DictionaryField(default=dict)),
            ],
            options={
                'verbose_name': 'form submission',
                'verbose_name_plural': 'form submissions',
                'db_table': 'publisher_form_submission',
                'ordering': ['id'],
                'abstract': False,
                'unique_together': {('external_id', 'portal_name')},
            },
        ),
    ]
