# Generated by Django 4.1.13 on 2024-11-20 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form_submission', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='formsubmission',
            name='session_id',
            field=models.CharField(default=None, max_length=256, null=True),
        ),
    ]
