# Generated by Django 4.1.13 on 2024-11-20 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form_submission', '0002_formsubmission_session_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='formsubmission',
            name='path',
            field=models.CharField(default=None, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='formsubmission',
            name='external_id',
            field=models.CharField(default=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='formsubmission',
            name='name',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='formsubmission',
            name='portal_name',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='formsubmission',
            name='session_id',
            field=models.CharField(default=None, max_length=50, null=True),
        ),
    ]
