# Generated by Django 4.1.13 on 2024-11-21 00:18

from django.db import migrations, models
import systems.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('form_submission', '0003_formsubmission_path_alter_formsubmission_external_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='formsubmission',
            name='nav_path',
            field=models.CharField(default=None, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='formsubmission',
            name='page',
            field=systems.models.fields.DictionaryField(default=dict),
        ),
    ]
