_base_model: &base_model
    base: id_resource
    key: id
    admin_roles: [data-admin]
    view_roles: [data-auditor]
    priority: 60

models:
    form_submission:
        <<: *base_model
        plural: form_submissions
        key: id
        id_fields: [external_id, portal_name]
        display: "<portal_name>:<external_id>"
        priority: 60
        fields:
            portal_name:
                type: string
            external_id:
                type: string
            session_id:
                type: string
            name:
                type: string
            fields:
                type: dict
