_base_model: &base_model
    base: id_resource
    key: id
    admin_roles: [data-admin]
    view_roles: [data-auditor]
    priority: 60

models:
    team_media_collection:
        <<: *base_model
        base: team
        plural: team_media_collections
        id_fields: [team, external_id]
        key: external_id
        display: "<external_id>: <name>"
        priority: 70
        fields:
            external_id:
                type: string
            description:
                type: text
            access_teams:
                type: list

    team_media:
        <<: *base_model
        base: team_media_collection
        plural: team_medias
        id_fields: [team_media_collection, external_id]
        key: id
        display: "<id>: <hash>"
        priority: 75
        fields:
            external_id:
                type: string
            type:
                type: string
                options:
                    default: file
            description:
                type: text
            hash:
                type: string
                options:
                    max_length: 65
            content:
                type: text
            sentences:
                type: list
            topics:
                type: dict

    form_submission:
        <<: *base_model
        plural: form_submissions
        key: id
        id_fields: [external_id, portal_name]
        display: "<portal_name>:<external_id>"
        priority: 60
        fields:
            portal_name:
                type: string
                options:
                    max_length: 100
            external_id:
                type: string
                options:
                    max_length: 50

            session_id:
                type: string
                options:
                    max_length: 50
            path:
                type: string
                options:
                    max_length: 1024
            name:
                type: string
                options:
                    max_length: 255
            fields:
                type: dict

            nav_path:
                type: string
                options:
                    max_length: 1024
            page:
                type: dict
