# Generated by Django 4.1.13 on 2024-12-02 06:04

from django.db import migrations, models
import django.db.models.deletion
import systems.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('team', '0002_team_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamMediaCollection',
            fields=[
                ('created', models.DateTimeField(editable=False, null=True)),
                ('updated', models.DateTimeField(editable=False, null=True)),
                ('id', models.CharField(editable=False, max_length=64, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=256)),
                ('external_id', models.CharField(default=None, max_length=256, null=True)),
                ('access_teams', systems.models.fields.ListField(default=list)),
                ('description', models.TextField(default=None, null=True)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(data_name)s', to='team.team')),
            ],
            options={
                'verbose_name': 'team media collection',
                'verbose_name_plural': 'team media collections',
                'db_table': 'publisher_team_media_collection',
                'ordering': ['external_id'],
                'abstract': False,
                'unique_together': {('team', 'external_id')},
            },
        ),
    ]
